### ISSUE TITLE
Ampersands being changed to &amp;

### ISSUE THREAD

**Issue by ammonitedigital** [nielsreijnders/textSplitter#4]
If the original text contains an ampersand in any of these formats:

```
&
&amp;
&#38;
```

The rendered ampersand is displayed as `&amp;` - as shown in the screenshot:

<img width="869" alt="" src="https://github.com/nielsreijnders/textSplitter/assets/95317376/08cdec07-049c-4722-9468-d89fb56e387b">

The expected output should be `&`

**Comment by nielsreijnders** [comment]
Apologies for the delay in getting back to you. Thank you for pointing out the issue; I appreciate your keen observation. The bug you mentioned has been addressed and rectified across all functions. If you encounter any further concerns or have additional questions, please don't hesitate to let me know. Your feedback is invaluable in ensuring the quality of our work.
